features:
  context_features:  
    - id_odsp
    - date
    - season
    - league
    - country
    - home_team
    - away_team
    - score_pre_80
    - score_ft
    - game_state_80
  selected_features:  
    - goal_diff_80
    # - home_shots_pre80
    # - away_shots_pre80
    # - home_fouls_pre80
    # - away_fouls_pre80
    # - home_corners_pre80
    # - away_corners_pre80
    # - home_yellow_cards_pre80
    # - away_yellow_cards_pre80
    # - home_sending_off_pre80
    # - away_sending_off_pre80
    - home_corners_70_75
    - away_corners_70_75
    - home_shots_70_75
    - away_shots_70_75
    # - home_fouls_70_75
    # - away_fouls_70_75
    - home_corners_75_80
    - away_corners_75_80
    - home_shots_75_80
    - away_shots_75_80
    # - home_fouls_75_80
    # - away_fouls_75_80
    # - odd_h
    # - odd_d
    # - odd_a
  constructed_features: 
    # - total_shots_pre_80
    # - total_fouls_pre_80
    # - total_yellow_cards_pre_80
    # - total_sending_off_pre_80
    # - total_corners_pre_80
    # - total_corners_70_75
    # - total_shots_70_75
    # - total_fouls_70_75
    # - total_corners_75_80
    # - total_shots_75_80
    # - total_fouls_75_80
    - odds_ratio
    - shot_to_corner_ratio_pre_80
    - home_urgency_to_attack
    - away_urgency_to_attack
    - home_momentum_to_attack
    - away_momentum_to_attack
    - attack_intensity
    - defensive_pressure
  target_variables:
    - home_corner_diff
    - away_corner_diff
    - corner_diff
    - target

model:
  classification:
    models: 
      - "random_forest" #start jsut with random forest for now
    grid_search: false  #If true... it overrides hyperparameters
    hyperparameters:
      random_forest:
        bootstrap: True
        # max_depth: 10
        # min_samples_leaf: 1
        # min_samples_split: 5
        n_estimators: 100
      # If a model is missing -> default settings will be used

  regression:
    models:
      - "random_forest"
    grid_search: true  #i.e. hyperparameters optimisation = on
    hyperparameters: {}  #empty dict = use default parameters

backtesting:
  initial_bankroll: 1000
  stake_fixed: 20
  kelly_fraction_cap: 0.1
  test_split_size: 500

paths:
  data: "data/aggregated_data.csv"
  total_corner_odds: "data/totalCorner_odds.csv"
  binary_predictions: "data/binary_predictions.csv"
  continuous_predictions: "data/continous_predictions.csv"
