track_num: 1

features:
  context_features:  
    - id_odsp
    - date
    - season
    - league
    - country
    - home_team
    - away_team
    - score_pre_80
    - score_ft
  selected_features:  
    # - goal_diff_80

    # *** Pre 80 Stats ***
    # - home_shots_pre80
    # - away_shots_pre80
    # - home_fouls_pre80
    # - away_fouls_pre80
    # - home_corners_pre80
    # - away_corners_pre80
    # - home_yellow_cards_pre80
    # - away_yellow_cards_pre80
    # - home_sending_off_pre80
    # - away_sending_off_pre80

    # *** Windowed Stats ***
    - home_corners_70_75
    - away_corners_70_75
    - home_shots_70_75
    - away_shots_70_75
    # - home_fouls_70_75
    # - away_fouls_70_75
    - home_corners_75_80
    - away_corners_75_80
    - home_shots_75_80
    - away_shots_75_80
    # - home_fouls_75_80
    # - away_fouls_75_80

    # *** Simple 2x1 Odds Data ***
    # - odd_h
    # - odd_d
    # - odd_a
  constructed_features: 
    # *** Game State Features ***
    - game_state_80_h
    - game_state_80_a
    - game_state_80_d

    # *** League Features ***
    # - league_england
    # - league_spain
    # - league_germany
    # - league_italy
    # - league_france
    - league_avg_corners
    # - league_avg_home_corners
    # - league_avg_away_corners

    # *** Goal Diff Features ***
    - abs_goal_diff_80
    - close_game_80
    - goal_diff_squared_80

    # *** Team Corner Averages ***
    - home_corners_for_avg  
    - home_corners_against_avg
    - away_corners_for_avg
    - away_corners_against_avg
    - home_post80_corners_for_avg  
    - home_post80_corners_against_avg
    - away_post80_corners_for_avg
    - away_post80_corners_against_avg

    # *** Total Features ***
    # - total_shots_pre_80
    # - total_fouls_pre_80
    # - total_yellow_cards_pre_80
    # - total_sending_off_pre_80
    # - total_corners_pre_80
    # - total_corners_70_75
    # - total_shots_70_75
    # - total_fouls_70_75
    # - total_corners_75_80
    # - total_shots_75_80
    # - total_fouls_75_80

    # *** Special Technical Indicator Features ***
    - odds_ratio
    - shot_to_corner_ratio_pre_80
    - home_urgency_to_attack
    - away_urgency_to_attack
    - home_momentum_to_attack
    - away_momentum_to_attack
    - attack_intensity
    - defensive_pressure
    - trailing_team_probability
  target_variable:
    - target
    # - corner_diff
  # possible_target_variables:
  #   - home_corner_diff
  #   - away_corner_diff
  #   - corner_diff
  #   - target
  #   - target2

model:
  classification:
    models: 
      - "random_forest"
      - "logistic_regression"
      - "svc"
      - "xgboost"
    grid_search: false  #If true... it overrides hyperparameters
    hyperparameters:
      random_forest:
        bootstrap: True
        # max_depth: None
        min_samples_leaf: 1
        min_samples_split: 2
        n_estimators: 200
      logistic_regression:
        solver: 'liblinear'
        penalty: 'l2'
        C: 1.0
      svc:
        C: 1.0
        kernel: 'rbf'
        gamma: 'scale'
      xgboost:
        n_estimators: 50
        max_depth: 3
        learning_rate: 0.1
        subsample: 0.8
      # If a model is missing -> default settings will be used

apply_calibration: false

backtesting:
  initial_bankroll: 1000
  fixed_bet_percent: 0.1
  target_mean_odds: 1.26
  bookie_margin: 0.05

paths:
  dataset: "../data/processed/track1_dataset.csv"
  total_corner_odds: "../data/totalCorner/totalCorner_odds.csv"