features:
  context_features:  
    - id_odsp
    - date
    - season
    - league
    - country
    - home_team
    - away_team
    - score_pre_80
    - score_ft
    # - game_state_80
  selected_features:  
    # - goal_diff_80
    - trailing_is_home
    # - leading_team_shots_pre80
    # - trailing_team_shots_pre80
    # - leading_team_fouls_pre80
    # - trailing_team_fouls_pre80
    # - leading_team_corners_pre80
    # - trailing_team_corners_pre80
    # - leading_team_yellow_cards_pre80
    # - trailing_team_yellow_cards_pre80
    # - leading_team_sending_off_pre80
    # - trailing_team_sending_off_pre80
    - leading_team_corners_70_75
    - trailing_team_corners_70_75
    - leading_team_shots_70_75
    - trailing_team_shots_70_75
    # - leading_team_fouls_70_75
    # - trailing_team_fouls_70_75
    - leading_team_corners_75_80
    - trailing_team_corners_75_80
    - leading_team_shots_75_80
    - trailing_team_shots_75_80
    # - leading_team_fouls_75_80
    # - trailing_team_fouls_75_80
    # - odd_h
    # - odd_d
    # - odd_a
  constructed_features: 
    # *** League Features ***
    # - league_england
    # - league_spain
    # - league_germany
    # - league_italy
    # - league_france
    # - league_avg_corners
    # - league_avg_home_corners
    # - league_avg_away_corners
    # - corner_rate_vs_avg
    # - trailing_team_corner_rate_vs_avg
    # - leading_team_corner_rate_vs_avg

    # - total_shots_pre_80
    # - total_fouls_pre_80
    # - total_yellow_cards_pre_80
    # - total_sending_off_pre_80
    # - total_corners_pre_80
    # - total_corners_70_75
    # - total_shots_70_75
    # - total_fouls_70_75
    # - total_corners_75_80
    # - total_shots_75_80
    # - total_fouls_75_80
    # - odds_ratio
    - trailing_team_attack_intensity
    - leading_team_attack_intensity
    - trailing_team_defensive_pressure
    - leading_team_defensive_pressure
    - trailing_team_shot_to_corner_ratio_pre_80
    - leading_team_shot_to_corner_ratio_pre_80
    - trailing_team_aggression_score_pre_80
    - leading_team_aggression_score_pre_80
    
    - leading_team_urgency_to_attack
    - trailing_team_urgency_to_attack
    - leading_team_momentum_to_attack
    - trailing_team_momentum_to_attack
    - trailing_team_probability
  target_variable:
    - target
    # - corner_diff
  # possible_target_variables:
  #   - leading_team_corner_diff
  #   - trailing_team_corner_diff
  #   - corner_diff
  #   - target
  #   - target2

model:
  classification:
    models: 
      - "random_forest"
      - "logistic_regression"
      - "svc"
      - "xgboost"
    grid_search: false  #If true... it overrides hyperparameters
    hyperparameters:
      random_forest:
        bootstrap: True
        # max_depth: None
        min_samples_leaf: 1
        min_samples_split: 2
        n_estimators: 200
      logistic_regression:
        solver: 'liblinear'
        penalty: 'l2'
        C: 1.0
      svc:
        C: 1.0
        kernel: 'rbf'
        gamma: 'scale'
      xgboost:
        n_estimators: 50
        max_depth: 3
        learning_rate: 0.1
        subsample: 0.8
      # If a model is missing -> default settings will be used

  regression:
    models:
      - "random_forest"
    grid_search: false  #i.e. hyperparameters optimisation = on
    hyperparameters: {}  #empty dict = use default parameters

backtesting:
  initial_bankroll: 1000
  fixed_bet_percent: 0.1

paths:
  dataset: "../data/processed/trailing_data.csv"
  total_corner_odds: "../data/external/totalCorner_odds.csv"